spring:
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    publisher-confirms: true
    virtual-host: /
  application:
    name: somersames-job
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/good?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


start:
    default:
        address: "上海"
        Cache-Control: "no-cache, no-store, max-age=0"
