spring:
  application:
    name: somersames-user
  redis:
    host: localhost
    port: 6379
    password: somersames
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    timeout: 0
#server:
#  port: 8082
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka